quarkus:
  http:
    port: ${SERVER_PORT:5050}
    cors-enabled: false
  application:
    name: ApiGateway
    version: 1.0.0


gateway:
  routes:
    - id: auth-manager
      uri: ${USER_SERVICE:http://localhost:5001}
      predicates:
        - Path=/api/auth/**
      filters:
        - LogFilter
    - id: user-manager
      uri: ${USER_SERVICE:http://localhost:5001}
      predicates:
        - Path=/api/users/**
      filters:
        - LogFilter
    - id: task-manager
      uri: ${TASK_SERVICE:http://localhost:5002}
      predicates:
        - Path=/api/tasks/**
      filters:
        - LogFilter
    - id: project-manager
      uri: ${PROJECT_SERVICE:http://localhost:5003}
      predicates:
        - Path=/api/projects/**
      filters:
        - LogFilter
    - id: analytics-service
      uri: ${ANALYTICS_SERVICE:http://localhost:5004}
      predicates:
        - Path=/api/analytics/**
      filters:
        - LogFilter